# Generated by Django 2.1.4 on 2019-01-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BylawModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raspr_date', models.DateField()),
                ('district', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=255)),
                ('inn', models.IntegerField()),
                ('performer', models.CharField(max_length=30)),
                ('check_type', models.CharField(max_length=50)),
                ('date_proved', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckTypesMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип проверок')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentsMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, verbose_name='Департаменты')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictsMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255, verbose_name='Районы')),
            ],
        ),
        migrations.CreateModel(
            name='PerformersMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer', models.CharField(max_length=255, verbose_name='Исполнители')),
            ],
        ),
    ]
