# Generated by Django 2.1.4 on 2019-01-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtsmenu',
            options={'verbose_name': 'Районы'},
        ),
        migrations.AlterField(
            model_name='districtsmenu',
            name='district',
            field=models.CharField(max_length=255, verbose_name='Район'),
        ),
    ]
