# Generated by Django 2.1.4 on 2019-01-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0002_auto_20190102_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictsMenu',
        ),
    ]
