# Generated by Django 2.1.4 on 2019-01-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0003_delete_districtsmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictsMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255, verbose_name='Район')),
            ],
            options={
                'verbose_name_plural': 'Районы список',
            },
        ),
    ]
