# Generated by Django 2.1.4 on 2019-01-03 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0004_districtsmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bylawmodel',
            options={'verbose_name_plural': 'Распоряжение форма'},
        ),
        migrations.AlterModelOptions(
            name='checktypesmenu',
            options={'verbose_name_plural': 'Тип проверок меню'},
        ),
        migrations.AlterModelOptions(
            name='departmentsmenu',
            options={'verbose_name_plural': 'Департаменты меню'},
        ),
        migrations.AlterModelOptions(
            name='districtsmenu',
            options={'verbose_name_plural': 'Районы меню'},
        ),
        migrations.AlterModelOptions(
            name='performersmenu',
            options={'verbose_name_plural': 'Исполнители меню'},
        ),
        migrations.AddField(
            model_name='bylawmodel',
            name='raspr_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bylawmodel',
            name='who_created',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='check_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='performer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checktypesmenu',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Тип проверки'),
        ),
        migrations.AlterField(
            model_name='departmentsmenu',
            name='department',
            field=models.CharField(max_length=255, verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='performersmenu',
            name='performer',
            field=models.CharField(max_length=255, verbose_name='Исполнитель'),
        ),
    ]
