# Generated by Django 2.1.4 on 2019-01-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0005_auto_20190103_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checktypesmenu',
            old_name='type',
            new_name='check_type',
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='check_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='date_proved',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='performer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='raspr_num',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='who_created',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
