# Generated by Django 2.1.4 on 2019-01-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0006_auto_20190103_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDocNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdn', models.CharField(max_length=255, verbose_name='Глобальный номер документов')),
            ],
        ),
    ]
