# Generated by Django 2.1.4 on 2019-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0007_globaldocnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldocnumber',
            name='gdn',
            field=models.CharField(default='00000', max_length=7, verbose_name='Глобальный номер документов'),
        ),
    ]
