# Generated by Django 2.1.4 on 2019-01-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0008_auto_20190104_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globaldocnumber',
            options={'verbose_name_plural': 'Глобальный номер документов'},
        ),
        migrations.AlterField(
            model_name='globaldocnumber',
            name='gdn',
            field=models.IntegerField(verbose_name='Глобальный номер документов'),
        ),
    ]
