# Generated by Django 2.1.4 on 2019-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0009_auto_20190104_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bylawmodel',
            name='district',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
    ]
