# Generated by Django 2.1.4 on 2019-01-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0010_auto_20190106_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bylawmodel',
            name='check_type',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='date_proved',
            field=models.DateField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='department',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='organization',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='performer',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='raspr_num',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='who_created',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
    ]
