# Generated by Django 2.1.4 on 2019-01-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0012_auto_20190106_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bylawmodel',
            name='check_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='date_proved',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='department',
            field=models.CharField(default='Unfilled', max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='district',
            field=models.CharField(default='Unfilled', max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='organization',
            field=models.CharField(default='Unfilled', max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='performer',
            field=models.CharField(default='Unfilled', max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='raspr_num',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='who_created',
            field=models.CharField(max_length=255),
        ),
    ]
