# Generated by Django 2.1.5 on 2019-01-15 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0013_auto_20190107_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bylawmodel',
            old_name='date_proved',
            new_name='date_proved_c',
        ),
        migrations.AddField(
            model_name='bylawmodel',
            name='date_proved_po',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
