# Generated by Django 2.1.5 on 2019-01-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0014_auto_20190115_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=255, verbose_name='Базис')),
            ],
            options={
                'verbose_name_plural': 'Базис меню',
            },
        ),
        migrations.CreateModel(
            name='LabSecurityMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_security', models.CharField(max_length=255, verbose_name='Лабораторное обеспечение')),
            ],
            options={
                'verbose_name_plural': 'Лабораторное обеспечение меню',
            },
        ),
        migrations.AddField(
            model_name='bylawmodel',
            name='base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bylawmodel',
            name='lab_security',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='check_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='inn',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='performer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='raspr_num',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='who_created',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
