# Generated by Django 2.1.5 on 2019-01-17 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0014_auto_20190115_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=255, verbose_name='Базис')),
            ],
            options={
                'verbose_name_plural': 'Базис меню',
            },
        ),
        migrations.CreateModel(
            name='LabSecurityMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_security', models.CharField(max_length=255, verbose_name='Лабораторное обеспечение')),
            ],
            options={
                'verbose_name_plural': 'Лабораторное обеспечение меню',
            },
        ),
        migrations.AddField(
            model_name='bylawmodel',
            name='base',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bylawmodel',
            name='lab_security',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
