# Generated by Django 2.1.5 on 2019-01-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0015_auto_20190120_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bylawmodel',
            name='base',
        ),
        migrations.RemoveField(
            model_name='bylawmodel',
            name='lab_security',
        ),
    ]
