# Generated by Django 2.1.5 on 2019-01-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0016_auto_20190120_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='bylawmodel',
            name='base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bylawmodel',
            name='lab_security',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
