# Generated by Django 2.1.5 on 2019-01-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0016_auto_20190117_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bylawmodel',
            name='base',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='check_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='lab_security',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='performer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bylawmodel',
            name='who_created',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
