# Generated by Django 2.1.5 on 2019-02-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0017_auto_20190120_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bylawmodel',
            name='raspr_num',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
