# Generated by Django 2.1.4 on 2019-03-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bylaw', '0018_auto_20190221_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseMenu',
        ),
        migrations.DeleteModel(
            name='CheckTypesMenu',
        ),
        migrations.DeleteModel(
            name='DepartmentsMenu',
        ),
        migrations.DeleteModel(
            name='DistrictsMenu',
        ),
        migrations.DeleteModel(
            name='LabSecurityMenu',
        ),
        migrations.DeleteModel(
            name='PerformersMenu',
        ),
    ]
