# Generated by Django 2.1.5 on 2019-01-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTypeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255, verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name_plural': 'Вид деятельности меню',
            },
        ),
        migrations.CreateModel(
            name='FizOrUrMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiz_or_ur', models.CharField(max_length=255, verbose_name='Физ. или Юр. лицо')),
            ],
            options={
                'verbose_name_plural': 'Физ. или Юр. лицо меню',
            },
        ),
        migrations.CreateModel(
            name='KoapArticleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koap_article', models.CharField(max_length=255, verbose_name='Статья КоАП РФ')),
            ],
            options={
                'verbose_name_plural': 'Статья КоАП РФ меню',
            },
        ),
        migrations.CreateModel(
            name='OrdinanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Unfilled', max_length=255)),
                ('ordinance_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('expiration', models.IntegerField()),
                ('fact_pay_date', models.DateField()),
                ('income_receipt_date', models.DateField()),
                ('organization', models.CharField(max_length=255)),
                ('fio_official_face', models.CharField(max_length=255)),
                ('passport_data', models.CharField(max_length=255)),
                ('inn', models.IntegerField()),
                ('protocol_date', models.DateField()),
                ('check_type', models.CharField(max_length=255)),
                ('performer', models.CharField(max_length=255)),
                ('fiz_or_ur', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('violation_type', models.CharField(max_length=255)),
                ('koap_article', models.CharField(max_length=255)),
                ('fine_sum', models.IntegerField()),
                ('payed', models.IntegerField()),
                ('debt', models.IntegerField()),
                ('dont_take_by_court_decision', models.CharField(max_length=255)),
                ('kbk', models.IntegerField()),
                ('kpp', models.IntegerField()),
                ('uin_formed', models.CharField(max_length=255)),
                ('raspr_num', models.CharField(max_length=255, unique=True)),
                ('who_created', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Распоряжение форма',
            },
        ),
        migrations.CreateModel(
            name='ViolationTypeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=255, verbose_name='Вид нарушения')),
            ],
            options={
                'verbose_name_plural': 'Вид нарушения меню',
            },
        ),
    ]
