# Generated by Django 2.1.5 on 2019-01-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordinancemodel',
            options={'verbose_name_plural': 'Постановление форма'},
        ),
        migrations.AddField(
            model_name='ordinancemodel',
            name='district',
            field=models.CharField(default='Unfilled', max_length=255),
        ),
        migrations.AlterField(
            model_name='ordinancemodel',
            name='debt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordinancemodel',
            name='expiration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordinancemodel',
            name='fine_sum',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordinancemodel',
            name='kbk',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordinancemodel',
            name='kpp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordinancemodel',
            name='payed',
            field=models.CharField(max_length=255),
        ),
    ]
