# Generated by Django 2.1.5 on 2019-03-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0002_auto_20190125_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDocNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdn', models.IntegerField(verbose_name='Глобальный номер документов')),
            ],
            options={
                'verbose_name_plural': 'Глобальный номер документов',
            },
        ),
    ]
