# Generated by Django 2.1.5 on 2019-03-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0004_coapkbkmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coapkbkmenu',
            name='coap',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Статья КоАП РФ'),
        ),
    ]
