# Generated by Django 2.1.5 on 2019-03-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0006_auto_20190308_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KoapArticleMenu',
        ),
    ]
