# Generated by Django 2.1.4 on 2019-03-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0007_delete_koaparticlemenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityTypeMenu',
        ),
        migrations.DeleteModel(
            name='CoapKbkMenu',
        ),
        migrations.DeleteModel(
            name='FizOrUrMenu',
        ),
        migrations.DeleteModel(
            name='ViolationTypeMenu',
        ),
        migrations.AlterField(
            model_name='globaldocnumber',
            name='gdn',
            field=models.IntegerField(verbose_name='Глобальный номер документов '),
        ),
    ]
