# Generated by Django 2.1.4 on 2019-03-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinance', '0008_auto_20190308_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinancemodel',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordinancemodel',
            name='district',
            field=models.CharField(max_length=255),
        ),
    ]
