# Generated by Django 2.1.4 on 2019-03-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemenu',
            options={'verbose_name_plural': 'Цель меню'},
        ),
        migrations.AlterModelOptions(
            name='labsecuritymenu',
            options={'verbose_name_plural': 'ФБУЗ меню'},
        ),
        migrations.AlterField(
            model_name='basemenu',
            name='base',
            field=models.CharField(max_length=255, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='labsecuritymenu',
            name='lab_security',
            field=models.CharField(max_length=255, verbose_name='ФБУЗ меню'),
        ),
    ]
