# Generated by Django 2.1.4 on 2019-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20190308_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoapKbkMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koap', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Статья КоАП РФ')),
                ('kbk', models.CharField(max_length=255, verbose_name='КБК')),
            ],
            options={
                'verbose_name_plural': 'Статья КоАП РФ - КБК меню',
            },
        ),
        migrations.DeleteModel(
            name='CoapKbkMenu',
        ),
    ]
